### PR TITLE
implemented editing of existing cards

### PR DESCRIPTION
**Pull request by perlus3**

### CODE REVIEW

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
## Code Review Report

### Task goal
Implement editing existing flashcards

### Requirements
- It should be able to turn on `Edit` mode when clicking on a pencil icon
- It should be able to `Cancel` editing
- It should be able to `Save` editing

### Review

#### src/App.tsx
The changes in this file are in line with the task requirements. The `FrontCard` and `BackCard` components are uncommented which allows for their rendering.

#### src/components/cards/BackCard.tsx
The changes in this file meet the task requirements. The `isEditing` state is used to toggle between the `EditCardBack` and the normal `BackCard` view. The pencil icon has been turned into a button that toggles the `isEditing` state, enabling the `Edit` mode. The `Cancel` and `Save` functionalities are handled in the `EditCardBack` component.

#### src/components/cards/EditCardBack.tsx
The changes in this file meet the task requirements. The `closeWindow` function is called after the editing is saved or cancelled, which would presumably close the editing mode. However, it's not clear from the provided diffs what this function does exactly. If it doesn't close the editing mode, then the requirement to be able to `Cancel` or `Save` editing is not met.

#### src/components/cards/EditCardFront.tsx
The changes in this file meet the task requirements. The `isDeleted` state is used to remove the card from view after deletion. The `renameStorageItem` function saves the changes made during editing, meeting the requirement to be able to `Save` editing. The `goBack` function is called after saving or cancelling, which would presumably close the editing mode. However, it's not clear from the provided diffs what this function does exactly. If it doesn't close the editing mode, then the requirement to be able to `Cancel` or `Save` editing is not met.

#### src/components/cards/FrontCard.tsx
The changes in this file meet the task requirements. The `isEditing` state is used to toggle between the `EditCardFront` and the normal `FrontCard` view. The pencil icon has been turned into a button that toggles the `isEditing` state, enabling the `Edit` mode. The `Cancel` and `Save` functionalities are handled in the `EditCardFront` component.

#### src/components/cards/NewCardFront.tsx
The changes in this file do not seem to be related to the task requirements and it's not clear how they affect the functionality of the application.

#### src/components/cards/NewCards.module.css
The changes in this file do not seem to be related to the task requirements and it's not clear how they affect the functionality of the application.

#### src/components/cards/SingleCard.module.css
The changes in this file do not seem to be related to the task requirements and it's not clear how they affect the functionality of the application.

### Conclusion
The code changes mostly cover the task requirements. However, it's not clear from the provided diffs if the `closeWindow` and `goBack` functions close the editing mode as required. If they don't, then the requirement to be able to `Cancel` or `Save` editing is not met.

**Review by NerdbordMentor — CHANGES_REQUESTED** [review]
# Code Review Report

## Task Requirements Validation

The task requirements were to implement editing existing flashcards. The requirements were:

1. It should be able to turn on `Edit` mode when clicking on a pencil icon.
2. It should be able to `Cancel` editing.
3. It should be able to `Save` editing.

Based on the provided code changes, the task requirements have been met:

1. The `Edit` mode is turned on when the pencil icon is clicked. This is implemented in `FrontCard.tsx` and `BackCard.tsx` by setting the `isEditing` state to true when the pencil icon is clicked.

2. The `Cancel` editing functionality is implemented in `EditCardFront.tsx` and `EditCardBack.tsx`. When the `Cancel` button is clicked, the `goBack` function is called which sets the `isEditing` state back to false.

3. The `Save` editing functionality is implemented in `EditCardFront.tsx` and `EditCardBack.tsx`. When the `Save` button is clicked, the changes are saved to the local storage.

## Code Changes Review

The code changes are generally well done and follow good practices. However, there are a few points that need attention:

1. In `EditCardBack.tsx`, there's a console.log statement left in the code. This should be removed as it's not good practice to leave debugging statements in production code.

2. In `EditCardFront.tsx`, there's a function `handleDeleteClick` that removes an item from local storage. This function does not check if the item exists before trying to remove it which could potentially cause an error.

3. In `NewCardFront.tsx`, the `editButton` image and its container div have been removed but they are still being imported at the top of the file. This import should be removed as well.

4. In `SingleCard.module.css`, the right property of the `.icon` class has been changed from 20px to -15px. This could potentially cause the icon to be displayed outside of its container.

5. In `NewCards.module.css`, the height of the `.input` class has been changed from 40px to 36px. This could potentially cause layout issues depending on the rest of the CSS.

6. In `App.tsx`, the `<FrontCard />` and `<BackCard />` components have been uncommented but no props are being passed to them. If these components require props, this could potentially cause an error.

Overall, the code changes cover the task requirements and are generally well done with a few minor issues that need attention.

**Review by Sumick — CHANGES_REQUESTED** [review]
We need to refactor this, as this approach with localStorage is very, non react way. Even if you  fetch data from API later, you will still have to handle local state. `localStorage` can be responsible for data persistence, but not for working with state in react, so `useState` should be your choice. Otherwise you lose all of the benefits like:

- performance: react's state management is optimized for performance, as it operates within the virtual DOM and updates are batched for efficient rendering.

- automatic reactivity: when the state changes using useState, React automatically triggers re-renders of the components that depend on that state, ensuring your UI is always up-to-date.

- type safety: React state can hold various types of data, and TypeScript can be used to enforce type safety, helping to catch type-related errors at compile time.

- encapsulation: state managed within React components is encapsulated and isolated to that component. It helps in avoiding unintended side effects and makes the component's behavior more predictable

So what you should do in this PR scope:

- [x] in you app.tsx you should have something like `const [flashcards, setFlashcards] = useState([])`, so it keeps all your created cards
- [x] when adding new card, add it to above state
- [x] then, based on cards in above state, render `SingleCard` components in the list
- [x] then by editing card, you should change card data (front or back) within this above state which keeps all cards
- [x] then you can remove your all localStorage related logic from codebase

And of course - you can use `localStorage` to persist that data if you want (you don't have to as it's not in the scope) - but persist only data that contains list of your flashcards.

**Review by NerdbordMentor — APPROVED** [review]
# Code Review Report

## Task goal
Implement editing existing flashcards

## Requirements
- It should be able to turn on `Edit` mode when clicking on a pencil icon
- It should be able to `Cancel` editing
- It should be able to `Save` editing

## Review

### src/App.tsx
The changes in this file cover the task requirements. The `editFlashCard` function allows for editing existing flashcards, and the `deleteCard` function allows for canceling the editing by removing the card. The `CardsList` component is passed the necessary props to perform these operations.

### src/components/cards/BackCard.tsx
The changes in this file cover the task requirements. The `isEditing` state variable is used to switch between viewing and editing modes. The `EditCardValue` component is used for editing the card's value, and it is passed the necessary props to perform this operation.

### src/components/cards/CardsList.tsx
The changes in this file cover the task requirements. The `flashCards` prop is used to render a list of `SingleCard` components, each of which can be edited.

### src/components/cards/EditCardBack.tsx
This file was removed, so there's no need to review it.

### src/components/cards/EditCardFront.tsx
This file was removed, so there's no need to review it.

### src/components/cards/EditCardName.tsx
This newly added file covers the task requirements

**Pull request merged**
